on: release
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@main
      - name: Build
        run: go build -o nz_azconnector nz_azconnector.go
      - name: Go Release Binary
        uses: ngs/go-release.action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: "386"
          GOOS: linux
          GO111MODULE: on
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@main
      - name: Build
        run: go build -o nz_azconnector nz_azconnector.go
      - name: Go Release Binary
        uses: ngs/go-release.action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: linux
